# This is a basic workflow that is manually triggered

name: Manual workflow (Build and Deploy)

on:
  workflow_dispatch:
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a yarn or npm command
      uses: Adzz/yarn_command_action@v2.0.0
      with:
        command: build
